cooldowns:
  duration: 24  # input is hours ie: 24 = 24 hour cooldown.
  messages:
    onCooldown: "&cYou are on cooldown. Cannot join or leave another town."
    remainingTime: "&eRemaining cooldown: %hours% hours."
    inviteCooldown: "&fCannot invite &c&l%player%&f as they are on cooldown. Remaining cooldown: &c&l%hours% &fhours."